# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aura < Formula
  desc "Aura - Modern SSH Manager for macOS"
  homepage "https://github.com/tissoni/aura-ssh-manager"
  version "0.1.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tissoni/aura-ssh-manager/releases/download/v0.1.0/aura_0.1.0_darwin_amd64.tar.gz"
    sha256 "83812e9771760252c314e6f8749ab0df89482e86f3423661c19699e93af21504"

    define_method(:install) do
      bin.install "aura"
      bash_completion.install "completions/autocomplete.sh" => "aura"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tissoni/aura-ssh-manager/releases/download/v0.1.0/aura_0.1.0_darwin_arm64.tar.gz"
    sha256 "2018335e486c28a361ccb76d0426ea8eb4b8eba9d53dc0e69557ba01637c5b89"

    define_method(:install) do
      bin.install "aura"
      bash_completion.install "completions/autocomplete.sh" => "aura"
    end
  end
end
