# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aura < Formula
  desc "Aura - Modern SSH Manager for macOS"
  homepage "https://github.com/tissoni/aura-ssh-manager"
  version "0.1.3"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tissoni/aura-ssh-manager/releases/download/v0.1.3/aura_0.1.3_darwin_amd64.tar.gz"
    sha256 "01ff58143c32541cecf1f82c090f8ff3ba59e53f5cdd4c09c0bc63b864a15e10"

    define_method(:install) do
      bin.install "aura"
      bash_completion.install "completions/autocomplete.sh" => "aura"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tissoni/aura-ssh-manager/releases/download/v0.1.3/aura_0.1.3_darwin_arm64.tar.gz"
    sha256 "7db7e65612fa1317130180b71ff9a821ec98e4bf80326ce1777ccef8d6432412"

    define_method(:install) do
      bin.install "aura"
      bash_completion.install "completions/autocomplete.sh" => "aura"
    end
  end
end
