# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aura < Formula
  desc "Aura - Modern SSH Manager for macOS"
  homepage "https://github.com/tissoni/aura-ssh-manager"
  version "1.3.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tissoni/aura-ssh-manager/releases/download/v1.3.0/aura_1.3.0_darwin_amd64.tar.gz"
    sha256 "93bbb024854e7774a73dffbdc6292bf1c8c62cdfcd2beba6e0bfd876de8cb9d3"

    define_method(:install) do
      bin.install "aura"
      bash_completion.install "completions/autocomplete.sh" => "aura"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tissoni/aura-ssh-manager/releases/download/v1.3.0/aura_1.3.0_darwin_arm64.tar.gz"
    sha256 "8f3265b420500651818da4aa70de890163bd6e97eac368311a530a22bc9b4d3e"

    define_method(:install) do
      bin.install "aura"
      bash_completion.install "completions/autocomplete.sh" => "aura"
    end
  end
end
